version: '3.9'

services:
  app:
    build: .
    container_name: app
    command: npm run start:dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks: 
      - jasamarga
  
  db:
    container_name: db
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    networks: 
      - jasamarga

volumes:
  pgdata: {}
networks:
  jasamarga: {}
