version: '3.9'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - ./.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks: 
      - jasamarga

volumes:
  pgdata: {}
networks:
  jasamarga: {}
